### PR TITLE
Allow user to edit profile

### LINKED ISSUE #6: Ability for users to edit own profile page

### PR DESCRIPTION
**Pull request by GabrielGramlich**
@svenJonis138 @KelseyStiff @cgisala @Sargazi77 

Does what the ticket says. Created new form and template, and updated two views.

### CODE REVIEW

**Comment by KelseyStiff** [comment]
looks great! however its allowing users to edit profiles when viewing profile - we should only allow edit when a users "edit profile button" is clicked

**Comment by GabrielGramlich** [comment]
@KelseyStiff edit button is in!

**Review by svenJonis138 — APPROVED** [review]
this looks good, everything is working for me locally!

**Comment by GabrielGramlich** [comment]
Going to allow user to update full name. Should be good to go in 10-15.

**Pull request merged**
