### PR TITLE
Adjusted models

### PR DESCRIPTION
**Pull request by svenJonis138**
changed most model fields back to blank=False
Note: you will have to makemigrations and possibly delete your local db after pulling this

### CODE REVIEW

**Comment by svenJonis138** [comment]
I may have been mistaken, I did migrations and didnt have any issues with my existing data...maybe we wont have to delete the db

**Comment by GabrielGramlich** [comment]
Solid work, I'm not seeing anything logically wrong. I did notice that you added in messages to be displayed to the add artist template, but don’t add any messages in the add artists view if the form is invalid. I'm gonna run over it a second time though, just in case.

**Comment by svenJonis138** [comment]
@GabrielGramlich if there is an issue with adding an artist those messages are generated in the save_artist view before it redirects to the add_artist template where they would be displayed, lmk if it isnt working that way

**Comment by KelseyStiff** [comment]
tested out, everything looks to be working so I'll merge changes now.

**Pull request merged**
