### PR TITLE
Using api

### LINKED ISSUE #2: Get initial data for app
How will this application get initial data? At the moment, shows, venues, and artists must be added through the administrator console. Should users be able to add venues, artists, shows? If so, how will you moderate this? Where else will your application get data from? Maybe you could focus on the Twin Cities and find a list of venues; and figure out some programatic method of getting data for shows, perhaps write a web scraper for First-Avenue.com and other popular venues?
Should users be able to create shows from artists and venues already in the database?

### PR DESCRIPTION
**Pull request by svenJonis138**
refined api returns, currently still adding any artist/venue you type in, but now makes the api call in the background and displays results in terminal, now we just need to decide how the user selects the result given to save. @KelseyStiff I am wondering if we can still do this action in the add_artist/add_venue form or if it needs to move to a different template.

### CODE REVIEW

**Comment by KelseyStiff** [comment]
i believe this can still be done in the add artist/add venue form..

however, I'm running into an issue trying to run/test your code
I think it has to do with requests not importing properly?


`  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kelseystiff/Documents/capstone/PROJECT_5/lmn/lmn/urls.py", line 5, in <module>
    from .views import views_main, views_artists, views_venues, views_notes, views_users
  File "/Users/kelseystiff/Documents/capstone/PROJECT_5/lmn/lmn/views/views_artists.py", line 11, in <module>
    from lmn.api_calls import search_mb_artist_by_name
  File "/Users/kelseystiff/Documents/capstone/PROJECT_5/lmn/lmn/api_calls.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by KelseyStiff** [comment]
@svenJonis138 awesome thank you! Testing it out now, is the venue attached to the API? the functionality is a little different than I thought but it is coming up with search results. Also looks like we have some merge conflicts, can you help me resolve those before we merge?

**Comment by KelseyStiff** [comment]
looks like everything is working now! ready to merge, can you review @GabrielGramlich

**Comment by GabrielGramlich** [comment]
Only thing I'm seeing worth changing is that there is no header above the results, which makes the formatting look a little off.

**Comment by GabrielGramlich** [comment]
Looks good. Couldn't break it. You rock. It's done. Officially. Closed.

**Pull request closed without merging**
